# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Compile mvn and npm and deploy with docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  git-pull:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: git pull
      run: cd /home/ubuntu/repos/ && sudo git pull
  mvn-compile:
    runs-on: self-hosted
    needs: git-pull
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: mvn compile
      run: sudo mvn -f /home/ubuntu/repos/react-java-mysql/backend compile
  mvn-test:
    runs-on: self-hosted
    needs: mvn-compile
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: mvn test
      run: sudo mvn -f /home/ubuntu/repos/react-java-mysql/backend test
  mvn-build:
    needs: [mvn-compile, mvn-test]
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: mvn build jar file
      run: sudo mvn -f /home/ubuntu/repos/react-java-mysql/backend clean install
  npm-ci:
    runs-on: self-hosted
    needs: git-pull
    steps:
    - uses: actions/checkout@v3
      with:
        cache: 'npm'
        cache-dependency-path: '/home/ubuntu/repos/react-java-mysql/frontend/package-lock.json'
    - name: npm clean install
      run: npm ci --prefix /home/ubuntu/repos/react-java-mysql/frontend/
  npm-build:
    needs: npm-ci
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
      with:
        cache: 'npm'
        cache-dependency-path: '/home/ubuntu/repos/react-java-mysql/frontend/package-lock.json'
    - name: npm run build
      run: npm run build --if-present --prefix /home/ubuntu/repos/react-java-mysql/frontend/
  docker-compose:
    needs: [mvn-build, npm-build]
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: docker stop front
      run: docker stop humid_frontend_1
    - name: docker stop back
      run: docker stop humid_backend_1
    - name: docker stop db
      run: docker stop humid_db_1
    - name: docker rm front
      run: docker rm humid_frontend_1
    - name: docker rm back
      run: docker rm humid_backend_1
    - name: docker rm db
      run: docker rm humid_db_1
    - name: docker-compose
      run: docker-compose -f /home/ubuntu/repos/react-java-mysql/compose.yaml -p humid up -d

