# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  compile:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: update
      run: cd /home/ubuntu/repos/ && sudo git pull
    - name: mvn compile
      run: sudo mvn -f /home/ubuntu/repos/react-java-mysql/backend compile
  test:
    runs-on: self-hosted
    needs: compile
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: mvn test
      run: sudo mvn -f /home/ubuntu/repos/react-java-mysql/backend test
  build:
    needs: [compile, test]
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: mvn build jar file
      run: sudo mvn -f /home/ubuntu/repos/react-java-mysql/backend clean install
  npm-ci:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
      with:
        cache: 'npm'
        cache-dependency-path: '/home/ubuntu/repos/frontend/package-lock.json'
    - name: npm clean install
      run: npm ci --prefix /home/ubuntu/repos/frontend/
  npm run build:
    needs: npm-ci
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
      with:
        cache: 'npm'
        cache-dependency-path: '/home/ubuntu/repos/frontend/package-lock.json'
    - name: npm run build
      run: npm run build --if-present --prefix /home/ubuntu/repos/frontend/
  deploy:
    needs: [build, npm]
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: docker ps test
      run: docker ps
